### ISSUE TITLE
Compilling error

### ISSUE THREAD

**Issue by ghost** [signetlabdei/lena-plus#1]
Dear sir
i have copied the whole repository to ns3 folder and replace with LTE folder and after that i run my normally written code for lte-ra-procedure. but it is giving me so many errors. like 
.../src/lte/test/epc/test-s1u-uplink.cc: In member function 'virtual void epcS1uUlTestCase::DoRun()';
error: no matching of this function for call
thanku__

**Comment by mychele** [comment]
Hi,
which version of ns-3 are you using?
Can you post a complete log of the error?
Michele

**Comment by ghost** [comment]
Hi

thanks alot for you concern.
I am using ns-3.26. i want to implement RACH network in LtE. The procedure
you mention on the website of coping the given repository to src/lte didn't
work.
can you guide me with this.
I want to calculte number of Rach attempts. It is also performed in the
paper you shared on the wwbsite.
i will be very thankful to you if you help me in this. I have a project on
this and i have to do all the work immediately.

thanks again
best regards

**Comment by mychele** [comment]
Hi,
you should try with ns-3.24.1 - ns-3.26 is not supported at the moment.
Michele

**Comment by ghost** [comment]
Thank you so much for your kind response.
I want some information about The calculation of Collision Probability in
the lte-enb-mac.cc file. can you provide me some documents or references
where you have calculated this value.

thanks again
waiting for the kind response
best regards

**Comment by mychele** [comment]
Hi, 
you can find an explanation here: http://ieeexplore.ieee.org/document/7511430/
Michele

**Comment by ghost** [comment]
Hi
Thanks for the sending very useful article regarding LENA+. I got very
useful information.

Now, i am little bit stuck in Contention resolution timer that where is it
added in the LENA+ Simulator. Please help me to know the procedure or
commands of Contention resolution timer in the LENA+.

Also, please tell me how the figures 4 and 5 are drawn in the manusript
"M2M Massive Access in LTE: RACH Performance
Evaluation in a Smart City Scenario". Let me know the commands.

I will be very thankful to you.

Thanks
Best Regards

**Comment by mychele** [comment]
Hi, 
take a look at the LteUeMac class: https://github.com/signetlabdei/lena-plus/blob/master/model/lte-ue-mac.cc#L358
For Fig. 4 and 5 I used some MATLAB scripts to analyze the output of the RA traces which are generated by several helper classes.
Best,
Michele

**Comment by ghost** [comment]
Thanks for sending the information. I need some more favor. Please send me
the MATLAB scripts to analyze the output of the RA Traces. Appreciate for
your overall help. Thanks

On Oct 17, 2017 3:01 AM, "Michele Polese" <notifications@github.com> wrote:

Hi,
take a look at the LteUeMac class: https://github.com/
signetlabdei/lena-plus/blob/master/model/lte-ue-mac.cc#L358
For Fig. 4 and 5 I used some MATLAB scripts to analyze the output of the RA
traces which are generated by several helper classes.
Best,
Michele

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/signetlabdei/lena-plus/issues/1#issuecomment-336973767>,
or mute the thread
